Updated celery config usage to new lowercase settings
mher/flower pull request #1185
Opened 2022-01-24 06:36 UTC by vinayinvicible

Ref: https://docs.celeryproject.org/en/v5.2.3/userguide/configuration.html#new-lowercase-settings

2022-02-25 06:51 UTC, vinayinvicible commented
@mher can you please check this

2022-07-08 05:54 UTC, auvipy requested changes
the tests might need adjustment as well

2022-07-08 06:48 UTC, vinayinvicible commented
@auvipy The is no issue with tests. I've rebased w.r.t. master and pushed the changes. Please check.

2022-07-08 10:04 UTC, auvipy approved these changes

2023-05-13 10:07 UTC, merged